POST http://localhost:3333/api/v1/groups
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBjODhmMjRiLTE0ZDMtNDNlNS1iYTk0LTNlZTRiMGU2MWVkZCIsImV4cCI6MTY4NDAwOTEzM30.iBvMbSS1n_f34D4fEgZAsjmNUvOFUrwzYsA1FCmO8kQ

{
  "name": "Java Masterclass",
  "description": "Master Java",
  "course_link": "http://java.com"
}

###
GET http://localhost:3333/api/v1/groups/search?text=java
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBjODhmMjRiLTE0ZDMtNDNlNS1iYTk0LTNlZTRiMGU2MWVkZCIsImV4cCI6MTY4NDAwOTEzM30.iBvMbSS1n_f34D4fEgZAsjmNUvOFUrwzYsA1FCmO8kQ

###
POST http://localhost:3333/api/v1/groups/32/join
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBjODhmMjRiLTE0ZDMtNDNlNS1iYTk0LTNlZTRiMGU2MWVkZCIsImV4cCI6MTY4NDAwOTEzM30.iBvMbSS1n_f34D4fEgZAsjmNUvOFUrwzYsA1FCmO8kQ

###
POST http://localhost:3333/api/v1/groups/12/leave
Content-Type: application/json
Authorization: Bearer dsfd