version: '3'

services:
  db:
    image: postgres:12
    restart: always
    environment:
      - PGUSER=studyconnect
      - POSTGRES_USER=studyconnect
      - POSTGRES_PASSWORD=studyconnect
    ports:
      - "5432:5432"
    volumes:
      - ./.db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  studyconnect-network:
    driver: bridge